apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:ZgPEWFmQMMU2S0VwEvCX7WdR6R8/NVj/jA==,iv:PS3bc+KjOANdXWd/OY6r5XOpP0/1HVLjzufxvzrGb98=,tag:+Bwi40zXa32jNusc1oPE6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-10T03:55:19Z"
    mac: ENC[AES256_GCM,data:PBVTMbka6f6Cy7UYB/yaaKVBJUfk7W+F3FwA8Oehdw8tam9eF4ZK2dDdE4o3E5bcCXBYgZq37WfEbbCG2GMDaFSitPV6OI5IU5R+wnYqFGGsT+KayOphLcvxQ121bEqb+tP+zs9XEiC8YiJW6WEFj4nb14IW9msFZZTw/MfIZ9w=,iv:flsoCq5shdEi3lO9AxhkhBif3AOV7B5RBP+SV77RPoM=,tag:Psf6Hd448g3Q+/dtrXNwqA==,type:str]
    pgp:
        - created_at: "2024-08-10T03:55:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA1vAhU2UtpVhAQv/RQRpf2yb7diCRC8Ee4hNoUyG3gbSSuW9o7LSpL+1YHVT
            qKjHrKzE3AqoB79Td/R0Lts0hoY+rXKR7fJKNDU+cUp0/xagsewkvS0I6rKACUXj
            piZydZI7OSDToDIgMJuIInFE+NnY21EZ3fXarwlQXufbBAmwP8nwehkCF4NIlOsX
            hgnZ0lZESqYctdqF1yI65bjQg2hbJRyTbSq65bbCbB3ETbsLNqJYglHbJjUb89ST
            Wn86GTClNIQbWKkFiyjKESM3wiqq8EJ55zglTcF1LhFiPj8EJesaCR50mbKBJQNd
            flqyuiVNwo7D34mjrhOwz7l4sUs30Ei1u/arXaUvxfYu3a3qXUxZNgwkw1E9jCsw
            sSbJmh7/fttEok5R6NGlGq7GUHGWTzMVFRoQV1F05jaw/IINLb5Mo0dzVbJllDk2
            KKG2lw7NLaFGapHx8p/nZtMXx6Y8PgIGSmMWEC+hkd+J31t09hDInS/eLSWrS+Ud
            bpHC3Hp2CqIj8iB0gAWI0lwB/wya4S8Sv7ezP6G2n6wIlkDfZbRODSSD32nou96M
            ObQmQQyDg0lca2WGcBQWSLafawULz4AKPzAR2Mw2QjzQN40EbC/5ztEG2EkffXIN
            Q3Zq5PgmOq3ngrs8Pg==
            =YHZW
            -----END PGP MESSAGE-----
          fp: F6444D94C406CF38
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
